name: Publish

on:
  workflow_dispatch:
  release:
    types:
      - published
      - released
  workflow_run:
    workflows: [Releaser]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  prepare-checkout:
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    name: Decide what ref to check out
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ github.event_name != 'workflow_run' && github.ref || steps.releaser.outputs.version }}
    steps:
      - name: Inspect triggering Releaser workflow run
        id: releaser
        if: github.event_name == 'workflow_run'
        uses: pl-strflt/uci/.github/actions/inspect-releaser@v0.0
        with:
          artifacts-url: ${{ github.event.workflow_run.artifacts_url }}

  build-and-push-image:
    name: Container
    needs: [prepare-checkout]
    if: needs.prepare_checkout.outputs.ref != ''
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.prepare_checkout.outputs.ref }}
          
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
          tags: |
            type=semver,pattern={{version}}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
